const Fields = {
  isActive: "isActive",
  isApproved: "isApproved",
  isLive: "isLive",
  email: "email",
  teammateId: "teammateId",
  teammateEmail: "teammateEmail",
  managerEmail: "managerEmail",
  managerId: "managerId",
  isVisible: "isVisible",
  status: "status",
  ON_GOING: "ON_GOING",
  ASSIGNED: "ASSIGNED",
  PAUSED: "PAUSED",
  DONE: "DONE",
  APPROVED: "APPROVED",
  ARCHIVED: "ARCHIVED",
  currentManagerId: "currentManagerId",
  createdBy: "createdBy",
  notificationId: "notificationId",
  corrections: "corrections",
  companyId: "companyId",
};
export { Fields };
