const Notifications = {
  NEW_TASK: "NEW_TASK",
  REQUEST_FROM_MANAGER: "REQUEST_FROM_MANAGER",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  ARCHIVED_TASK: "ARCHIVED_TASK",
  CORRECTION_ADDED: "CORRECTION_ADDED",
  QUERY_ADDED: "QUERY_ADDED",
  QUERY_REPLIED: "QUERY_REPLIED",
  DONE_TASK: "DONE_TASK",
  APPROVED_TASK: "APPROVED_TASK",
  NEW_TASK_REASSIGNED:"NEW_TASK_REASSIGNED",
  DEADLINE_UPDATED: "DEADLINE_UPDATED",
};

export { Notifications };
